#+Title: Kubernetes Networking
#+Author: kangxiaoning
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js@3.8.0
#+REVEAL_VERSION: 3.8.0
#+REVEAL_THEME: white
#+REVEAL_PLUGINS: (chalkboard highlight search)
#+OPTIONS:  reveal_slide_number:c/t toc:nil num:nil


* Objectives
  #+ATTR_REVEAL: :frag (appear)
  + Understand networking and Linux primitives that power Kubernetes
  + Understand the Container Network Interface (CNI) project
  + Understand the Kubernetes networking model


* Agenda
  + TCP/IP and OSI


* TCP/IP and OSI

** 
  :PROPERTIES:
  :reveal_background: ./images/tcpip-and-osi.png
  :reveal_background_size: 500px
  :END:

** IP Header
*** 
    :PROPERTIES:
    :reveal_background: ./images/ipv4-header.svg
    :reveal_background_size: 1000px
    :END:

*** IP Header fields
    - *Internet Header Length (IHL)*
      - The IPv4 header has a variable size due to the optional 14th field option.
    - *Identification*
      - This is the identification field and is used for uniquely identifying the group of fragments of a single IP datagram.

#+REVEAL: split

    - *Flags*
      - This is used to control or identify fragments. In order from most significant to least:
      - bit 0: Reserved, set to zero
      - bit 1: Do not Fragment
      - bit 2: More Fragments
    - *Time To Live (TTL)*
      - An 8-bit time to live field helps prevent datagrams from going in circles on a network.


*** IP Header in wireshark
*** 
    :PROPERTIES:
    :reveal_background: ./images/ipv4-header-wireshark.png
    :reveal_background_size: 1400px
    :END:

** TCP Header
*** 
    :PROPERTIES:
    :reveal_background: ./images/tcp-header.svg
    :reveal_background_size: 1000px
    :END:

*** TCP Header fields
    - *Sequence number (32 bits)*
      - If the SYN flag is set, this is the initial sequence number. The sequence number of the first data byte and the acknowledged number in the corresponding ACK is this sequence number plus 1. It is also used to reassemble data if it arrives out of order.

#+REVEAL: split

    - *Acknowledgment number (32 bits)*
      - If the ACK flag is set, then this field’s value is the next sequence number of the ACK the sender is expecting. This acknowledges receipt of all preceding bytes (if any). Each end’s first ACK acknowledges the other end’s initial sequence number itself, but no data has been sent.

#+REVEAL: split

    - *Flags (9 bits)*
      - *NS–ECN-nonce*: Concealment protection.
      - *CWR*: Congestion Window Reduced; the sender reduced its sending rate.
      - *ECE*: ECN Echo; the sender received an earlier congestion notification.
      - *URG*: Urgent; the Urgent Pointer field is valid, but this is rarely used.
      - *ACK*: Acknowledgment; the Acknowledgment Number field is valid and is always on after a connection is established.

#+REVEAL: split

      - *PSH*: Push; the receiver should pass this data to the application as soon as possible.
      - *RST*: Reset the connection or connection abort, usually because of an error.
      - *SYN*: Synchronize sequence numbers to initiate a connection.
      - *FIN*: The sender of the segment is finished sending data to its peer.

#+REVEAL: split

    - *Window size (16 bits)*
      - This is the size of the receive window.
    - *Options*
      - Variable 0–320 bits, in units of 32 bits.

    - *Padding*
      - The TCP header padding is used to ensure that the TCP header ends, and data begins on a 32-bit boundary.

*** TCP Header in wireshark
*** 
    :PROPERTIES:
    :reveal_background: ./images/tcp-header-wireshark.png
    :reveal_background_trans: slide
    :END:

*** TCP State
*** 
    :PROPERTIES:
    :reveal_background: ./images/tcp-state.svg
    :reveal_background_size: 1000px
    :END:

*** TCP State

    - *LISTEN* (server)
      - Represents waiting for a connection request from any remote TCP and port

    - *SYN-SENT* (client)
      - Represents waiting for a matching connection request after sending a connection request

    #+REVEAL: split

    - *SYN-RECEIVED* (server)
      - Represents waiting for a confirming connection request acknowledgment after having both received and sent a connection request

    - *ESTABLISHED* (both server and client)
      - Represents an open connection; data received can be delivered to the user—the intermediate state for the data transfer phase of the connection

    #+REVEAL: split

    - *FIN-WAIT-1* (both server and client)
      - Represents waiting for a connection termination request from the remote host

    - *FIN-WAIT-2* (both server and client)
      - Represents waiting for a connection termination request from the remote TCP

    - *CLOSE-WAIT* (both server and client)
      - Represents waiting for a local user’s connection termination request

    #+REVEAL: split

    - *CLOSING* (both server and client)
      - Represents waiting for a connection termination request acknowledgment from the remote TCP

    - *LAST-ACK* (both server and client)
      - Represents waiting for an acknowledgment of the connection termination request previously sent to the remote host

    #+REVEAL: split

    - *TIME-WAIT* (either server or client)
      - Represents waiting for enough time to pass to ensure the remote host received the acknowledgment of its connection termination request

    - *CLOSED* (both server and client)
      - Represents no connection state at all

** TLS Handshake
** 
   :PROPERTIES:
   :reveal_background: ./images/tls-handshake.png
   :reveal_background_size: 800px
   :END:

** 
   - 1. *ClientHello*: This contains the cipher suites supported by the client and a random number.
   - 2. *ServerHello*: This message contains the cipher it supports and a random number.
   - 3. *ServerCertificate*: This contains the server’s certificate and its server public key.

   #+REVEAL: split

   - 4. *ServerHelloDone*: This is the end of the ServerHello. If the client receives a request for its certificate, it sends a ClientCertificate message.
   - 5. *ClientKeyExchange*: Based on the server’s random number, our client generates a random premaster secret, encrypts it with the server’s public key certificate, and sends it to the server.
   - 6. *Key Generation*: The client and server generate a master secret from the premaster secret and exchange random values.

   #+REVEAL: split

   - 7. *ChangeCipherSpec*: Now the client and server swap their ChangeCipherSpec to begin using the new keys for encryption.
   - 8. *Finished Client*: The client sends the finished message to confirm that the key exchange and authentication were successful.
   - 9. *Finished Server*: Now, the server sends the finished message to the client to end the handshake.

** 
   :PROPERTIES:
   :reveal_background: ./images/tls-01.png
   :END:

** 
   :PROPERTIES:
   :reveal_background: ./images/tls-02.png
   :END:

** 
   :PROPERTIES:
   :reveal_background: ./images/tls-03.png
   :END:

** 
   :PROPERTIES:
   :reveal_background: ./images/tls-04.png
   :END:

** VXLAN Header
** 
   :PROPERTIES:
   :reveal_background: ./images/vxlan-header.png
   :reveal_background_size: 1000px
   :END:

** VXLAN Header in wireshark
** 
   :PROPERTIES:
   :reveal_background: ./images/vxlan-header-wireshark.png
   :reveal_background_trans: slide
   :END:
